apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auth
  namespace: argocd
  labels:
    me.kundun: auth
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/homelab
        revision: HEAD
        directories:
          - path: k8s/infra/auth/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        me.kundun: controllers
    spec:
      project: auth
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/luminosita/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
