apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    me.kundun: infrastructure
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/homelab
        revision: HEAD
        directories:
          - path: k8s/infra/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        me.kundun: infrastructure
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/luminosita/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      # syncPolicy:
      #   syncOptions:
      #     - ApplyOutOfSyncOnly=true
        # automated:
        #   selfHeal: true
        #   prune: true
