apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-emisia
  namespace: gateway
spec:
  dnsNames:
    - "*.emisia.net"
    - emisia.net
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-emisia
  usages:
    - digital signature
    - key encipherment
