apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: gateway
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.50.220
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-gateway
      hostname: "*.emisia.net"
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-emisia
      allowedRoutes:
        namespaces:
          from: All
    - protocol: HTTPS
      port: 443
      name: https-domain-gateway
      hostname: emisia.net
      tls:
        certificateRefs:
          - kind: Secret
            name: cert-emisia
      allowedRoutes:
        namespaces:
          from: All
