realm: coturn.stonegarden.dev
replicaCount: 1
extraOptions:
  - --listening-ip=0.0.0.0

certificate:
  enabled: true
  dnsName: coturn.stonegarden.dev
  issuerName: cloudflare-cluster-issuer

service:
  annotations:
    io.cilium/lb-ipam-ips: 192.168.50.226
  type: LoadBalancer

users:
  - name: netbird
    secretKeyRef:
      name: netbird-turn-credentials
      key: password
