auth:
  authority: https://keycloak.emisia.net/realms/homelab
  audience: netbird
  device:
    provider: hosted
    audience: netbird
    authority: https://keycloak.emisia.net/realms/homelab
    clientID: netbird
    deviceAuthorizationEndpoint: https://keycloak.emisia.net/realms/homelab/protocol/openid-connect/auth
    tokenEndpoint: https://keycloak.emisia.net/realms/homelab/protocol/openid-connect/token
    scope: openid
    useIDToken: false

idp:
  managerType: keycloak
  clientID: netbird-backend
  secretKeyRef:
    name: netbird-backend-oidc-credentials
    key: clientSecret
  grantType: client_credentials
  adminEndpoint: https://keycloak.emisia.net/admin/realms/homelab
  tokenEndpoint: https://keycloak.emisia.net/realms/homelab/protocol/openid-connect/token

management:
  image:
    tag: 0.28.9 # renovate: docker=docker.io/netbirdio/management
  nodeSelector:
    topology.kubernetes.io/zone: abel
  ingress:
    enabled: false

signal:
  image:
    tag: 0.28.9 # renovate: docker=docker.io/netbirdio/signal
  nodeSelector:
    topology.kubernetes.io/zone: abel
  uri: netbird.emisia.net:443
  protocol: https
  ingress:
    enabled: false

stun:
  uri: stun:coturn.emisia.net:3478

turn:
  uri: turn:coturn.emisia.net:3478
  user: netbird
  secretKeyRef:
    name: netbird-turn-credentials
    key: password
