apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
  labels:
    me.kundun: application
spec:
  generators:
    - git:
        repoURL: https://github.com/luminosita/homelab
        revision: HEAD
        directories:
          - path: k8s/apps/dev/whoami
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        me.kundun: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: applications
      source:
        repoURL: https://github.com/luminosita/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: argocd
      # syncPolicy:
        # syncOptions:
        #   - ApplyOutOfSyncOnly=true
        # automated:
        #   selfHeal: true
        #   prune: true
